(function(root){
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=n=>n==null?'Pendiente':new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:2}).format(n);
 const date=d=>new Date(d).toLocaleString('es-CO',{timeZone:'America/Bogota'});
 function totals(items){return {pedidos:new Set(items.map(i=>i.pedido_id)).size,unidades:items.reduce((s,i)=>s+Number(i.cantidad),0),costo:items.some(i=>i.costo==null)?null:items.reduce((s,i)=>s+i.cantidad*i.costo,0),retail:items.reduce((s,i)=>s+i.cantidad*i.precio,0)};}
 function groups(items,by){const map=new Map();for(const i of items){const value=i[by]||'Sin dato registrado';if(!map.has(value))map.set(value,[]);map.get(value).push(i);}return [...map].sort(([a],[b])=>a.localeCompare(b,'es'));}
 function table(items){return '<div class="table-wrap"><table class="list-preview"><thead><tr><th>Pedido / destino</th><th>Referencia</th><th>Cantidad</th><th>Proveedor</th><th>Costo unitario</th><th>Precio retail</th><th>Total costo</th></tr></thead><tbody>'+items.map(i=>'<tr><td data-label="Pedido / destino">'+esc(i.numero)+'<br><b>'+esc(i.tienda||i.tienda_codigo)+'</b><br>'+esc(i.ciudad||'Ciudad no registrada')+'</td><td data-label="Referencia">'+esc(i.referencia)+'</td><td data-label="Cantidad">'+i.cantidad+'</td><td data-label="Proveedor">'+esc(i.proveedor||'Pendiente')+'</td><td data-label="Costo unitario">'+money(i.costo)+'</td><td data-label="Precio retail">'+money(i.precio)+'</td><td data-label="Total costo">'+money(i.costo==null?null:i.cantidad*i.costo)+'</td></tr>').join('')+'</tbody></table></div>';}
 function grouped(items,by){return groups(items,by).map(([name,rows])=>'<article class="card"><h3>'+esc(name)+'</h3>'+table(rows)+'<p class="total">Costo: '+money(totals(rows).costo)+'</p></article>').join('')||'<p class="empty">No hay pedidos sin cierre. Los cierres anteriores permanecen en el historial.</p>';}
 function exportRows(items){return [['Pedido','Fecha','Proveedor','Ciudad','Tienda','Referencia','Cantidad','Costo unitario','Precio retail','Total costo','Total retail'],...items.map(i=>[i.numero,i.fecha,i.proveedor,i.ciudad,i.tienda,i.referencia,i.cantidad,i.costo,i.precio,i.costo==null?'':i.cantidad*i.costo,i.cantidad*i.precio])];}
 function summarizeReferences(items){const map=new Map();for(const item of items){const key=item.producto_id||item.referencia;if(!map.has(key))map.set(key,{referencia:item.referencia,cantidad:0,total:0,missingCost:false,costs:new Map()});const row=map.get(key),quantity=Number(item.cantidad),cost=item.costo==null?null:Number(item.costo);row.cantidad+=quantity;if(cost==null)row.missingCost=true;else row.total+=quantity*cost;row.costs.set(cost,(row.costs.get(cost)||0)+quantity);}return [...map.values()].sort((a,b)=>String(a.referencia).localeCompare(String(b.referencia),'es')).map(({costs,missingCost,...row})=>({...row,total:missingCost?null:row.total,costos:[...costs].map(([costo,cantidad])=>({costo,cantidad}))}));}
 function providerReportTables(items){const supplierTables=groups(items,'proveedor').map(([provider,providerRows])=>({heading:`Proveedor ${provider}`,headers:['Ciudad','Referencia','Cantidad total','Costo unitario / composición','Total proveedor'],rows:groups(providerRows,'ciudad').flatMap(([city,cityRows])=>summarizeReferences(cityRows).map(row=>[city,row.referencia,row.cantidad,row.costos.map(part=>`${part.cantidad} × ${money(part.costo)}`).join(' / '),row.total]))}));const internal={heading:'Distribución interna',headers:['Proveedor','Ciudad','Tienda','Pedido','Referencia','Cantidad','Precio retail'],rows:[...items].sort((a,b)=>String(a.proveedor).localeCompare(String(b.proveedor),'es')||String(a.ciudad).localeCompare(String(b.ciudad),'es')||String(a.tienda).localeCompare(String(b.tienda),'es')).map(item=>[item.proveedor||'Proveedor pendiente',item.ciudad||'Ciudad no registrada',item.tienda||item.tienda_codigo,item.numero,item.referencia,item.cantidad,item.precio])};return [...supplierTables,internal];}
 function providerExportRows(items){return [['Proveedor','Ciudad','Referencia','Cantidad total','Costo unitario / composición','Total proveedor'],...providerReportTables(items).filter(table=>table.heading!=='Distribución interna').flatMap(table=>table.rows.map(row=>[table.heading.replace(/^Proveedor /,''),...row]))];}
 function mount({sb,container}){
  if(container._refreshB2BClosure)return container._refreshB2BClosure();
  let preview=null,history=[],key=null,selected=null;
  container.innerHTML='<div class="list-heading"><div><h2>Pedidos recibidos y cierre de período</h2><p class="sub">Consolida las solicitudes y envía el reporte a Comercial y Gestión. No confirma compras ni recepción de mercancía.</p></div><button class="btn" data-reload>Actualizar pedidos y cierres</button></div><div class="grid" data-summary></div><div class="close-toolbar"><label class="b2b-visually-hidden" for="b2bOrderGrouping">Ver pedidos</label><select id="b2bOrderGrouping" data-group><option value="proveedor">Ver pedidos por proveedor</option><option value="ciudad">Ver pedidos por ciudad</option><option value="tienda">Ver pedidos por tienda</option></select><button class="btn" data-download>Descargar consolidado (CSV)</button><button class="btn primary" data-close-period>Revisar y cerrar período</button></div><p class="notice">El Excel separa una hoja por proveedor y consolida el pedido por ciudad. La hoja <b>Distribución interna</b> conserva el reparto por tienda para preparar las remisiones.</p><div data-orders></div><p data-status role="status" aria-live="polite"></p><details><summary><b>Historial de cierres</b></summary><div data-history></div><div data-detail></div></details><dialog data-dialog class="b2b-close-dialog"><h2>Confirmar cierre de período</h2><p data-confirm-summary></p><p>El reporte se enviará a <b>comercial@crediteksas.com</b> y <b>gestion@crediteksas.com</b>. Los pedidos nuevos quedarán para el siguiente cierre.</p><p>Este corte no marca pedidos como entregados, no genera compras y no modifica inventario o cartera.</p><div class="actions"><button class="btn" data-cancel>Volver sin cerrar</button><button class="btn primary" data-confirm>Cerrar período y enviar consolidado</button></div><p data-dialog-status role="status"></p></dialog>';
  const $=s=>container.querySelector(s),status=$('[data-status]'),dialog=$('[data-dialog]');
  const previousReportData=root.KoraReportData;
  root.KoraReportData={async prepareExcel(report){const active=!document.getElementById('workspace-pedidos')?.hidden;if(!active||!preview?.items?.length)return previousReportData?.prepareExcel?previousReportData.prepareExcel(report):report;return {...report,tables:providerReportTables(preview.items)};}};
  function render(){const items=preview?.items||[],t=totals(items);$('[data-summary]').innerHTML=[['Pedidos sin cierre',t.pedidos],['Unidades solicitadas',t.unidades],['Costo proveedor',money(t.costo)],['Valor retail',money(t.retail)]].map(([label,value])=>'<div class="card"><small>'+label+'</small><div class="price">'+value+'</div></div>').join('');$('[data-orders]').innerHTML=grouped(items,$('[data-group]').value);$('[data-close-period]').disabled=!items.length||t.costo==null||!preview||preview.pedidos>1000;$('[data-download]').disabled=!items.length;
   $('[data-history]').innerHTML=history.length?'<div class="table-wrap"><table class="list-preview"><thead><tr><th>Cierre</th><th>Fecha</th><th>Correo</th><th>Consultar</th></tr></thead><tbody>'+history.map(h=>'<tr><td data-label="Cierre">CIE-'+String(h.consecutivo).padStart(6,'0')+'</td><td data-label="Fecha">'+esc(date(h.creado_at))+'</td><td data-label="Correo">'+esc(h.correo_estado)+(['error','incierto'].includes(h.correo_estado)?' · revisar entrega; no crear otro cierre':'')+'</td><td data-label="Consultar"><button class="btn" data-history-id="'+h.id+'">Ver y descargar</button></td></tr>').join('')+'</tbody></table></div>':'<p class="empty">Aún no hay cierres en KORA. Esta consulta no incorpora automáticamente el historial del portal anterior.</p>';
   $('[data-history]').querySelectorAll('[data-history-id]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{const {data,error}=await sb.from('b2b_cierres').select('id,consecutivo,reporte').eq('id',button.dataset.historyId).single();if(error)throw error;selected=data;$('[data-detail]').innerHTML='<h3>CIE-'+String(data.consecutivo).padStart(6,'0')+' · copia guardada al cerrar</h3><button class="btn" data-export-history>Descargar este cierre</button>'+grouped(data.reporte.items,'proveedor');$('[data-export-history]').onclick=()=>root.KoraB2BListsUI.download(providerExportRows(selected.reporte.items),'KORA-Cierre-'+selected.consecutivo+'-por-ciudad.csv');}catch(e){status.textContent='No se pudo consultar el cierre: '+e.message;}finally{button.disabled=false;}});
  }
  async function refresh(){
   $('[data-reload]').disabled=true;$('[data-close-period]').disabled=true;$('[data-download]').disabled=true;status.textContent='Consultando solicitudes y cierres…';
   try{const [result,saved]=await Promise.all([sb.rpc('vista_previa_cierre_b2b'),root.KoraB2BComparativo.all(()=>sb.from('b2b_cierres').select('id,consecutivo,creado_at,correo_estado,correo_enviado_at').order('creado_at',{ascending:false}).order('id'))]);if(result.error)throw result.error;preview=result.data;history=saved;key=null;render();status.textContent=preview.items.some(i=>i.costo==null)?'Hay pedidos sin costo de origen: revísalos antes de cerrar.':preview.pedidos>1000?'El período supera 1000 pedidos; requiere un corte por lotes antes de cerrar.':'Consulta actualizada. Los pedidos ya incluidos en un cierre no se vuelven a contar.';}catch(e){preview=null;status.textContent='No se pudo cargar el cierre: '+e.message;}finally{$('[data-reload]').disabled=false;}
  }
  $('[data-group]').onchange=()=>{if(preview)$('[data-orders]').innerHTML=grouped(preview.items,$('[data-group]').value);};
  $('[data-reload]').onclick=refresh;$('[data-download]').onclick=()=>root.KoraB2BListsUI.download(providerExportRows(preview.items),'KORA-Pedidos-por-proveedor-y-ciudad.csv');
  $('[data-close-period]').onclick=()=>{if(!preview?.items.length)return;const t=totals(preview.items);key||=crypto.randomUUID();$('[data-confirm-summary]').textContent=t.pedidos+' pedidos · '+t.unidades+' unidades · costo proveedor '+money(t.costo)+'. Revisa el detalle mostrado antes de confirmar.';$('[data-dialog-status]').textContent='';dialog.showModal();};
  $('[data-cancel]').onclick=()=>dialog.close();
  $('[data-confirm]').onclick=async()=>{if(!preview||!key)return;const confirm=$('[data-confirm]');confirm.disabled=true;$('[data-cancel]').disabled=true;$('[data-reload]').disabled=true;try{const {data,error}=await sb.rpc('cerrar_periodo_pedidos_b2b',{p_pedidos:preview.pedido_ids,p_huella:preview.huella,p_key:key});if(error)throw error;dialog.close();await refresh();status.textContent=data.numero+' guardado. Correo en cola para Comercial y Gestión; consulta su estado en el historial.';}catch(e){$('[data-dialog-status]').textContent='No se confirmó el cierre: '+e.message+' Si hubo un fallo de conexión, reintenta aquí: no se duplicará.';}finally{confirm.disabled=false;$('[data-cancel]').disabled=false;$('[data-reload]').disabled=false;}};
  container._refreshB2BClosure=refresh;return refresh();
 }
 // Filtro comercial por nombre, igual al portal anterior; no altera el catálogo.
 function brand(name){const n=String(name||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();if(/\b(REDMI|POCO|XIAOMI)\b/.test(n))return 'XIAOMI';if(/\b(MOTO|MOTOROLA)\b/.test(n))return 'MOTOROLA';if(/\b(IPHONE|IPAD|APPLE)\b/.test(n))return 'APPLE';return ['SAMSUNG','HONOR','INFINIX','TECNO','NOKIA','JBL','BOSE','OPPO','ZTE','REALME','VIVO','HUAWEI','ITEL','ALCATEL','TCL','LENOVO'].find(b=>new RegExp('\\b'+b+'\\b').test(n))||'OTRAS';}
 const api={totals,groups,grouped,exportRows,summarizeReferences,providerReportTables,providerExportRows,brand,mount};if(typeof module==='object'&&module.exports)module.exports=api;else root.KoraB2BCierres=api;
})(typeof globalThis!=='undefined'?globalThis:this);
