export const NOVA_FEATURES=Object.freeze(['BUSCAR_CLIENTE','CREAR_CLIENTE','PERFIL_CLIENTE','VENTAS_ASOCIADAS','VALIDACIONES_PLATAFORMA','SEMAFORO','RECOMENDACION_PRE_CREDITO']);
export const NOVA_PLATFORM_CHECKS=Object.freeze({PAYJOY:'REAL_READ_ONLY',ALO:'PENDING_ADAPTER',ADDI:'PENDING_ADAPTER',KREDIYA:'PENDING_ADAPTER'});
