import {auraAuth} from './aura-auth-otp-20260802.mjs';
import {AURA_CAPABILITIES,hasAuraCapability} from './aura-access-policy.mjs';
const moduleAccess=await auraAuth.restore();
const clientRoutes=new Set(['search','profile','sales','validations','portfolio']);
const capabilityForRoute=route=>route==='search'?AURA_CAPABILITIES.CONSULTAS:clientRoutes.has(route)?AURA_CAPABILITIES.CLIENTES:AURA_CAPABILITIES.NOVA;
const routeAllowed=route=>hasAuraCapability(moduleAccess,capabilityForRoute(route));
const requestedRoute=location.hash.slice(1)||'summary';
const app=document.querySelector('#nova-app');
const state={route:routeAllowed(requestedRoute)?requestedRoute:'denied',profile:null,check:null,loading:false,message:''};
const h=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
const money=value=>value==null?'No disponible':new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(value);
const head=(title,subtitle,action)=>`<header class="page-head"><div><h1>${title}</h1><p>${subtitle}</p></div><div class="recommend"><small>ACCIÓN RECOMENDADA</small>${action}</div></header>`;
const tabs=()=>{const routes=hasAuraCapability(moduleAccess,AURA_CAPABILITIES.NOVA)?[['summary','Resumen'],['requests','Solicitudes'],['reviews','Pendientes de revisión'],['customers','Clientes'],['validations','Validaciones'],['history','Historial'],['settings','Configuración']]:[['search','Buscar / Registrar']];return`<nav class="registry-tabs">${routes.map(([route,label])=>`<button class="${state.route===route?'active':''}" data-route="${route}">${label}</button>`).join('')}</nav>`};
const api=async(url,options)=>{const response=await fetch(url,{cache:'no-store',...options,headers:{'content-type':'application/json',...(options?.headers||{})}});if(!response.ok)throw new Error('sandbox unavailable');return response.json();};
function searchView(){return`${head('Registro / Consulta de clientes','Búsqueda operativa por cédula/DNI o teléfono','Busca antes de crear. Los identificadores técnicos PayJoy permanecen del lado servidor.')}<form class="card client-search" data-search-form><input name="query" inputmode="numeric" autocomplete="off" placeholder="Cédula / DNI o teléfono" aria-label="Cédula, DNI o teléfono" required><button class="primary">Buscar cliente</button></form><div class="privacy-note">PII mínima · documento y teléfono enmascarados · IMEI y API key nunca llegan al navegador.</div>${state.message?`<p class="settings-warning">${h(state.message)}</p>`:''}${state.profile?profileSummary():createForm()}`}
function createForm(){return`<section class="card empty-state"><h2>Cliente no encontrado</h2><p>Registra únicamente datos ficticios en este sandbox.</p></section><form class="card registry-form" data-create-form><label>Nombre<input name="name" required></label><label>Documento<input name="document" inputmode="numeric" required></label><label>Teléfono<input name="phone" inputmode="tel" required></label><label>Ciudad<input name="city" required></label><label>Tienda<select name="store"><option>Corozal 01</option><option>Corozal 02</option><option>Chinu 1</option><option>Tolu</option></select></label><label>Origen<select name="origin"><option>AURA_SANDBOX</option><option>TIENDA_SANDBOX</option></select></label><label class="wide"><span><input type="checkbox" name="authorization" required> Autorización de tratamiento/contacto confirmada</span></label><button class="primary wide">Crear cliente ficticio</button></form>`}
function profileSummary(){const c=state.profile.customer;return`<section class="card panel"><h2>${h(c.name)}</h2><div class="profile-summary">${[['Documento',c.document],['Teléfono',c.phone],['Ciudad',c.city],['Tienda origen',c.store],['Fecha creación',c.created_at],['Autorización',c.authorization?'VIGENTE':'NO REGISTRADA']].map(([l,v])=>`<div class="detail"><small>${l}</small><b>${h(v)}</b></div>`).join('')}</div><div class="registry-actions"><button class="primary" data-route="validations">Consultar PayJoy</button><button class="secondary" data-route="portfolio">Abrir Cartera</button></div></section>`}
function profileView(){if(!state.profile)return searchView();return`${head('Perfil cliente','Vista consolidada con PII mínima','Revisa autorización, ventas, validaciones y obligaciones antes de continuar.')} ${profileSummary()}<section class="grid-2"><article class="card panel"><h2>Historial de gestión</h2><p>Eventos sandbox auditados sin PII en metadata.</p></article><article class="card panel"><h2>Autorizaciones</h2><p class="${state.profile.customer.authorization?'authorization-ok':'authorization-missing'}">${state.profile.customer.authorization?'Tratamiento/contacto autorizado':'Revisión obligatoria de autorización'}</p></article></section>`}
function salesView(){const rows=state.profile?.sales||[];return`${head('Ventas asociadas','Relación explícita cliente → venta','Verifica plataforma y estado; los localizadores técnicos están ocultos.')}<div class="table-wrap registry-table"><table><thead><tr><th>Fecha</th><th>Tienda</th><th>Plataforma</th><th>Referencia</th><th>Estado</th><th>Valor</th><th>ID interno</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${h(x.date)}</td><td>${h(x.store)}</td><td>${h(x.platform)}</td><td>${h(x.reference)}</td><td>${h(x.status)}</td><td>${money(x.value)}</td><td>${h(x.id)}</td></tr>`).join('')}</tbody></table></div>`}
function payjoyBlock(){const p=state.check;if(!p)return`<section class="card empty-state"><h2>PAYJOY</h2><p>Aún no se ha ejecutado la validación sandbox.</p><button class="primary" data-payjoy-check>Consultar ahora</button></section>`;return`<section class="card payjoy-block ${p.signal.toLowerCase()}"><span class="signal ${p.signal.toLowerCase()}">${p.signal==='RED'?'SEÑAL ALTA DE RIESGO PAYJOY':p.signal}</span><h2>PAYJOY · ${p.available===false?'NO DISPONIBLE':p.match?'ENCONTRADO':'NO ENCONTRADO'}</h2><div class="profile-summary">${[['Contrato',p.contract_present?'SÍ':'NO'],['Saldo',money(p.remaining_balance)],['Historial',p.payment_history_available?'DISPONIBLE':'NO'],['Último pago',p.last_payment_at||'No disponible'],['Número de pagos',p.payment_count],['Costo mensual',money(p.monthly_cost)],['Costo semanal',money(p.weekly_cost)],['Plazo',p.months??'No disponible'],['Actualizado',p.checked_at]].map(([l,v])=>`<div class="detail"><small>${l}</small><b>${h(v)}</b></div>`).join('')}</div><div class="client-action"><small>SEÑAL PAYJOY · NO ES MORA CERTIFICADA · DECISIÓN: PENDIENTE</small><b>${h(p.recommendation)}</b><span>${h(p.reason_code)}</span></div><button class="secondary" data-payjoy-check>Actualizar consulta</button></section>`}
function validationsView(){return`${head('Validaciones','PayJoy Check · gateway server-side sandbox','Usa la señal como apoyo; nunca como rechazo automático definitivo.')} ${payjoyBlock()}<section class="card panel"><h2>Próximas validaciones</h2><p>ALO · Addi · Krediya — no configuradas.</p></section>`}
function portfolioView(){const rows=state.profile?.obligations||[];return`${head('Cartera del cliente','Obligaciones relacionadas y estado de gestión','Abre la ficha de obligación en AURA Cartera para continuar la gestión.')}<div class="table-wrap"><table><thead><tr><th>Obligación</th><th>Plataforma</th><th>Estado</th><th>Saldo</th><th>Acción</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${h(x.id)}</td><td>${h(x.platform)}</td><td>${h(x.status)}</td><td>${money(x.balance)}</td><td><a class="primary" href="aura-cartera.html#customers">Abrir ficha de obligación</a></td></tr>`).join('')}</tbody></table></div>`}
const summaryView=()=>`${head('NOVA Autorizaciones','Resumen operativo sandbox','Prioriza solicitudes pendientes de revisión; NOVA no toma decisiones finales automáticas.')}<section class="grid-2"><article class="card panel"><h2>Solicitudes</h2><p>Número, tendencia y acción recomendada disponibles cuando existan solicitudes sandbox.</p></article><article class="card panel"><h2>Estado de canales</h2><p>SANDBOX · SIN WHATSAPP REAL · PayJoy de solo lectura.</p></article></section>`;
const requestsView=()=>`${head('Solicitudes','Nueva autorización y seguimiento','Busca o registra al cliente antes de iniciar las validaciones.')} ${searchView()}`;
const reviewsView=()=>`${head('Pendientes de revisión','Casos que requieren decisión humana','Revisa señales y motivos; aprobar o negar permanece deshabilitado en sandbox.')}<section class="card empty-state"><h2>Revisión humana</h2><p>Las señales YELLOW y RED crean casos OPEN sin decidir automáticamente.</p></section>`;
const customersView=()=>`${head('Clientes','Consulta operativa con PII mínima','Usa documento o teléfono; nunca solicites IMEI al asesor.')} ${searchView()}`;
const historyView=()=>`${head('Historial','Trazabilidad de autorizaciones','Consulta estados sin exponer información sensible.')}<section class="card empty-state"><h2>Auditoría sandbox</h2><p>Eventos técnicos sin PII disponibles para revisión autorizada.</p></section>`;
const settingsView=()=>`${head('Configuración','Políticas y adaptadores de NOVA','Mantén ALO, Addi y Krediya bloqueados hasta disponer de adaptadores reales.')}<section class="card panel"><h2>Plataformas</h2><p>PayJoy: REAL READ-ONLY · ALO: PENDING_ADAPTER · Addi: PENDING_ADAPTER · Krediya: PENDING_ADAPTER</p><p class="settings-warning">SANDBOX — SIN ENVÍOS Y SIN DECISIÓN AUTOMÁTICA DEFINITIVA</p></section>`;
const deniedView=()=>`${head('Acceso denegado','HTTP 403 · esta ruta no está autorizada para tu rol','Regresa al panel de AURA y abre únicamente los módulos habilitados.')}`;
const views={summary:summaryView,requests:requestsView,reviews:reviewsView,customers:customersView,validations:validationsView,history:historyView,settings:settingsView,search:searchView,profile:profileView,sales:salesView,portfolio:portfolioView,denied:deniedView};
function render(){app.innerHTML=(state.route==='denied'?'':tabs())+(views[state.route]||deniedView)();bind();}
function bind(){document.querySelectorAll('[data-route]').forEach(node=>node.addEventListener('click',()=>{const route=node.dataset.route;state.route=routeAllowed(route)?route:'denied';location.hash=route;render()}));document.querySelector('[data-search-form]')?.addEventListener('submit',async event=>{event.preventDefault();state.loading=true;try{const data=await api(`/api/nova/search?query=${encodeURIComponent(new FormData(event.target).get('query'))}`);state.profile=data.profile;state.check=null;state.message=data.profile?'Cliente encontrado':'No existe: puede crear un registro ficticio';}catch{state.message='Sandbox no disponible';}render();});document.querySelector('[data-create-form]')?.addEventListener('submit',async event=>{event.preventDefault();const input=Object.fromEntries(new FormData(event.target));input.authorization=Boolean(input.authorization);try{const data=await api('/api/nova/customers',{method:'POST',body:JSON.stringify(input)});state.profile=data.profile;state.route=routeAllowed('profile')?'profile':'denied';location.hash='profile';state.message='Cliente ficticio creado';}catch{state.message='No fue posible crear en sandbox';}render();});document.querySelectorAll('[data-payjoy-check]').forEach(node=>node.addEventListener('click',async()=>{try{const data=await api('/api/nova/payjoy-check',{method:'POST',body:JSON.stringify({customer_id:state.profile.customer.id})});state.check=data.check;}catch{state.check={match:false,contract_present:false,remaining_balance:null,payment_history_available:false,payment_count:0,last_payment_at:null,monthly_cost:null,weekly_cost:null,months:null,signal:'REVIEW',reason_code:'PAYJOY_UNAVAILABLE',recommendation:'Revisión requerida',checked_at:new Date().toISOString()};}render();}));}
addEventListener('hashchange',()=>{const route=location.hash.slice(1)||'summary';state.route=routeAllowed(route)?route:'denied';render()});render();
