import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const read=name=>readFile(new URL(`../../creditek/agentes/${name}`,import.meta.url),'utf8');

test('shell muestra Clientes NOVA y Cartera únicamente al owner',async()=>{const shell=await read('index.html');for(const section of ['Clientes','NOVA Autorizaciones','Cartera'])assert.match(shell,new RegExp(`data-aura-owner-module[^>]*>${section}<`));assert.match(shell,/OWNER_ONLY_APP_IDS = new Set\(\['clientes_sandbox', 'nova_sandbox', 'cartera_sandbox'\]\)/);assert.match(shell,/element\.hidden = !isAuraOwner\(\)/);assert.match(shell,/OWNER_ONLY_APP_IDS\.has\(appId\) && !isAuraOwner\(\)/);});
test('Clientes tiene cuatro rutas y NOVA siete rutas vigentes',async()=>{const shell=await read('index.html');for(const route of ['search','profile','sales','validations'])assert.match(shell,new RegExp(`openClientsModule\\('${route}'`));for(const route of ['summary','requests','reviews','customers','validations','history','settings'])assert.match(shell,new RegExp(`openNovaModule\\('${route}'`));assert.match(shell,/\['summary', 'requests', 'reviews', 'customers', 'validations', 'history', 'settings'\]/);});
test('Cartera conserva once rutas',async()=>{const shell=await read('index.html');const routes=['summary','daily','segments','customers','reconciliation','promises','reports','conversations','optouts','kpis','settings'];for(const route of routes)assert.match(shell,new RegExp(`openCarteraModule\\('${route}'`));});
test('NOVA y Cartera anuncian canal pendiente y cero envíos',async()=>{const [nova,cartera,carteraJs]=await Promise.all([read('aura-nova.html'),read('aura-cartera.html'),read('aura-cartera.js')]);assert.match(nova,/Canal WhatsApp pendiente de activación Meta/);assert.match(cartera,/Canal Creditek Pagos pendiente de activación Meta/);assert.match(carteraJs,/ENVIAR REAL — DESHABILITADO/);assert.doesNotMatch(`${nova}\n${cartera}\n${carteraJs}`,/graph\.facebook\.com|WHATSAPP_TOKEN|PHONE_NUMBER_ID/);});
test('configuración registra módulos owner review sin cambiar Sofía',async()=>{const config=await read('aura-module-config.js');assert.match(config,/appId: 'clientes_sandbox'/);assert.match(config,/appId: 'nova_sandbox'/);assert.match(config,/appId: 'cartera_sandbox'/);assert.equal((config.match(/permission: 'owner\.review'/g)||[]).length,3);assert.match(config,/permission: 'sofia\.use'/);});
