import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const read=name=>readFile(new URL(`../../creditek/agentes/${name}`,import.meta.url),'utf8');

test('shell muestra Clientes NOVA y Cartera por capacidades explícitas',async()=>{const shell=await read('index.html');for(const permission of ['consultas.read','nova.read','cartera.read'])assert.match(shell,new RegExp(`data-aura-capability="${permission.replace('.','\\.')}"`));assert.match(shell,/hasAuraCapability\(auraAccess, capability\)/);assert.doesNotMatch(shell,/OWNER_ONLY_APP_IDS/);});
test('Clientes tiene cuatro rutas y NOVA siete rutas vigentes',async()=>{const shell=await read('index.html');for(const route of ['search','profile','sales','validations'])assert.match(shell,new RegExp(`openClientsModule\\('${route}'`));for(const route of ['summary','requests','reviews','customers','validations','history','settings'])assert.match(shell,new RegExp(`openNovaModule\\('${route}'`));assert.match(shell,/\['summary', 'requests', 'reviews', 'customers', 'validations', 'history', 'settings'\]/);});
test('Cartera conserva once rutas',async()=>{const shell=await read('index.html');const routes=['summary','daily','segments','customers','reconciliation','promises','reports','conversations','optouts','kpis','settings'];for(const route of routes)assert.match(shell,new RegExp(`openCarteraModule\\('${route}'`));});
test('NOVA y Cartera anuncian canal pendiente y cero envíos',async()=>{const [nova,cartera,carteraJs]=await Promise.all([read('aura-nova.html'),read('aura-cartera.html'),read('aura-cartera.js')]);assert.match(nova,/Canal WhatsApp pendiente de activación Meta/);assert.match(cartera,/Canal Creditek Pagos pendiente de activación Meta/);assert.match(carteraJs,/ENVIAR REAL — DESHABILITADO/);assert.doesNotMatch(`${nova}\n${cartera}\n${carteraJs}`,/graph\.facebook\.com|WHATSAPP_TOKEN|PHONE_NUMBER_ID/);});
test('configuración registra permisos canónicos sin cambiar Sofía',async()=>{const config=await read('aura-module-config.js');for(const app of ['clientes','nova','cartera'])assert.match(config,new RegExp(`appId: '${app}'`));for(const permission of ['clientes.read','nova.read','cartera.read'])assert.match(config,new RegExp(`permission: '${permission.replace('.','\\.')}'`));assert.match(config,/permission: 'sofia\.use'/);});
