import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {createClientRegistry,createPayJoySignal,normalizePhone,PayJoyCustomerCheck,resolveLocators,sandboxFixtures} from '../../src/nova/sandbox/client-registry.mjs';
const root=path.resolve(import.meta.dirname,'../..'),read=file=>readFile(path.join(root,file),'utf8');
function setup(){const f=sandboxFixtures();const service=new PayJoyCustomerCheck({gateway:f.gateway,clock:()=>new Date('2026-08-26T12:00:00Z')});return{f,registry:createClientRegistry({...f,payjoyService:service,clock:()=>new Date('2026-08-26T12:00:00Z')}),service};}

test('busca cliente por cédula normalizada',()=>{const{registry}=setup();assert.equal(registry.search('1.000.000.001')?.id,'SANDBOX-C-1');});
test('busca cliente por teléfono y normaliza prefijo Colombia',()=>{const{registry}=setup();assert.equal(normalizePhone('+57 300-000-0002'),'3000000002');assert.equal(registry.search('+57 300-000-0002')?.id,'SANDBOX-C-2');});
test('cliente inexistente devuelve null',()=>{const{registry}=setup();assert.equal(registry.search('9999999999'),null);});
test('crea cliente mínimo solo dentro del registro sandbox',()=>{const{registry}=setup();const c=registry.create({name:'Fixture Nuevo',document:'1000000099',phone:'3000000099',city:'Corozal',store:'Corozal 01',authorization:true});assert.equal(c.authorization,true);assert.equal(registry.customers.length,4);});
test('asocia ventas y oculta localizadores sensibles del perfil',()=>{const{registry}=setup();const p=registry.profile('SANDBOX-C-1');assert.equal(p.sales.length,1);assert.doesNotMatch(JSON.stringify(p),/SIMULATED-IMEI|imei_internal|phone_internal|device_tag_internal|external_customer_id/);});
test('resuelve IMEI antes que cualquier otro localizador',()=>{const{f}=setup();const r=resolveLocators(f.customers[0],f.sales);assert.equal(r.type,'IMEI');});
test('PayJoy sin venta previa produce revisión segura',async()=>{const{registry}=setup();const r=await registry.payjoyCheck('SANDBOX-C-3');assert.equal(r.signal,'REVIEW');assert.equal(r.reason_code,'PAYJOY_NOT_FOUND');});
test('Lookup PASS normaliza contrato, saldo e historial',async()=>{const{registry}=setup();const r=await registry.payjoyCheck('SANDBOX-C-1');assert.equal(r.match,true);assert.equal(r.contract_present,true);assert.equal(r.remaining_balance,420000);assert.equal(r.payment_count,3);});
test('PayJoy no disponible nunca provoca rechazo automático',async()=>{const f=sandboxFixtures();const service=new PayJoyCustomerCheck({gateway:{lookup:async()=>{throw new Error('offline')}}});const registry=createClientRegistry({...f,payjoyService:service});const r=await registry.payjoyCheck('SANDBOX-C-1');assert.equal(r.signal,'REVIEW');assert.equal(r.recommendation,'Revisión requerida');});
test('señal verde permite continuar a evaluación',()=>{const r=createPayJoySignal({match:true,contract_present:true,payment_history_available:true,payment_count:2,remaining_balance:10,last_payment_at:'2026-08-20'});assert.deepEqual([r.signal,r.recommendation],['OK','Puede continuar a evaluación']);});
test('señal amarilla exige revisión con evidencia incompleta',()=>{const r=createPayJoySignal({match:true,contract_present:true,payment_history_available:false,payment_count:0,remaining_balance:10});assert.equal(r.signal,'REVIEW');});
test('señal roja es advertencia reversible, no rechazo automático',()=>{const r=createPayJoySignal({match:true,contract_present:true,payment_history_available:true,payment_count:0,remaining_balance:10});assert.deepEqual([r.signal,r.recommendation],['HIGH_RISK_SIGNAL','NO AUTORIZAR SIN REVISIÓN']);});
test('dato mayor a 60 minutos queda stale y fuerza nueva consulta',async()=>{let calls=0,now=new Date('2026-08-26T10:00:00Z');const f=sandboxFixtures();const service=new PayJoyCustomerCheck({gateway:{lookup:async x=>{calls++;return f.gateway.lookup(x)}},clock:()=>now});await service.check(f.customers[0],f.sales);now=new Date('2026-08-26T11:01:00Z');await service.check(f.customers[0],f.sales);assert.equal(calls,2);});
test('auditoría usa eventos permitidos sin PII en metadata',async()=>{const{registry}=setup();registry.search('1000000001');await registry.payjoyCheck('SANDBOX-C-1');assert.deepEqual(registry.audit.map(x=>x.event),['CLIENT_SEARCHED','PAYJOY_CHECK_STARTED','PAYJOY_CHECK_COMPLETED','PAYJOY_SIGNAL_CREATED']);assert.ok(registry.audit.every(x=>x.metadata.pii===false));});
test('frontend integra cinco vistas, vínculo Cartera y ninguna clave o IMEI',async()=>{const [shell,html,js,server]=await Promise.all([read('creditek/agentes/index.html'),read('creditek/agentes/aura-nova.html'),read('creditek/agentes/aura-nova.js'),read('scripts/serve-aura-cartera-sandbox.mjs')]);for(const route of ['search','profile','sales','validations','portfolio'])assert.match(shell,new RegExp(`openNovaModule\\('${route}'`));assert.match(js,/aura-cartera\.html#customers/);assert.match(html,/SANDBOX · NOVA AUTORIZACIONES/);assert.match(server,/safePayJoyCheck/);assert.doesNotMatch(`${html}\n${js}\n${server}`,/apiKey|creditek-payjoy-api|IMEI completo|SIMULATED-IMEI|partner\.payjoy\.com/i);});
