import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const read=p=>readFileSync(new URL(p,import.meta.url),'utf8');
const migration=read('../../supabase/migrations/20260918234622_b2b_catalogo_sin_colores.sql');
const seed=JSON.parse(read('../fixtures/b2b-colores-20260918.json'));
const uid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
test('colores: una referencia, menor costo real, fuente congelada y roles protegidos',async()=>{
 const db=new PGlite();
 try {
  const source=read('./b2b-listas.test.mjs'),start=source.indexOf('await db.'+'exec(`create role anon');
  const fixture=source.slice(start+15,source.indexOf('`);',start)).replace(/\$\{uid\((\d+)\)\}/g,(_,n)=>uid(n));
  await db.exec(fixture);
  await db.exec('create role service_role;grant select on origenes to authenticated;');
  await db.exec(`create policy admin_lines on pedido_b2b_items for select to authenticated using(exists(select 1 from perfiles where id=auth.uid() and activo and rol in ('gerencia','auditoria')));`);
  await db.exec(read('../../supabase/migrations/20260917174237_listas_precios_pedidos_kora.sql'));
  const q=async(sql,args=[])=>(await db.query(sql,args)).rows;
  const ids=new Map();
  for(const [i,p] of seed.entries()){
   ids.set(p.codigo,uid(100+i));
   await q('insert into productos values($1,$2,$3,$4,$5,true)',[uid(100+i),p.codigo,p.nombre,'ACCESORIO','https://example.test/product.jpg']);
  }
  // Definitions compile without sending mail. No scheduler is created in tests.
  const mail=read('../../supabase/migrations/20260917220854_b2b_pedidos_correo.sql');
  await db.exec(mail.slice(mail.indexOf('create function public.kora_claim_b2b_pedido_mail'),mail.indexOf('create function public.kora_finish_b2b_pedido_mail')));
  const cierre=read('../../supabase/migrations/20260918152850_b2b_cierre_periodo_consolidado.sql');
  await db.exec(cierre.slice(cierre.indexOf('create function public.vista_previa_cierre_b2b'),cierre.indexOf('revoke all on function public.vista_previa_cierre_b2b')));
  await db.exec('revoke all on function public.kora_claim_b2b_pedido_mail(uuid,uuid) from public,anon,authenticated; grant execute on function public.kora_claim_b2b_pedido_mail(uuid,uuid) to service_role;');
  const beforeProducts=await q('select * from productos order by id');
  const white=ids.get('2GE3003'),blue=ids.get('BHR08OJGL'),canonical=ids.get('K26-1E0C63353C4B');
  const as=async n=>db.exec(`reset role;select set_config('request.jwt.claim.sub','${uid(n)}',false);set role authenticated;`);
  const publish=async(rows,h)=>q('select publicar_lista_b2b($1,$2,$3,$4::jsonb) r',['lista',h.repeat(64),'catalogo',JSON.stringify(rows)]);
  const offer=(id,s,cost)=>({producto_id:id,proveedor_id:uid(s),costo:cost,precio_tienda:cost+20000});
  await as(1);
  await publish([offer(white,20,85000),offer(blue,20,80000),offer(canonical,21,71000),offer(ids.get('BHR07Y5GL'),20,170000),offer(ids.get('BHR07PYGL'),20,170000)],'a');
  await as(3);
  const old=(await q('select * from catalogo_pedidos_b2b() where id=$1',[white]))[0];
  const order=async (p,key=uid(900+Number(p.id===canonical)))=>q('select crear_pedido_catalogo_b2b($1::jsonb,null,$2) r',[JSON.stringify([{producto_id:p.id,cantidad:2,version_precio:p.version_precio,precio_catalogo:Number(p.precio_guia)}]),key]);
  await order(old);
  await db.exec('reset role');
  const beforeOffers=await q('select * from b2b_ofertas order by id');
  const beforeOrders=await q('select * from pedido_b2b_items order by id');
  const beforeSources=await q('select * from b2b_pedido_fuente order by pedido_item_id');
  await db.exec(migration);
  assert.deepEqual(await q('select * from productos order by id'),beforeProducts);
  assert.deepEqual(await q('select * from b2b_ofertas order by id'),beforeOffers);
  assert.deepEqual(await q('select * from pedido_b2b_items order by id'),beforeOrders);
  assert.deepEqual(await q('select * from b2b_pedido_fuente order by pedido_item_id'),beforeSources);
  assert.equal((await q('select * from b2b_referencias_catalogo')).length,56);
  assert.equal((await q('select distinct referencia_id from b2b_referencias_catalogo')).length,28);
  const defs=await q("select proname,pg_get_functiondef(oid) body,proacl from pg_proc where proname in ('kora_claim_b2b_pedido_mail','vista_previa_cierre_b2b')");
  assert.equal(defs.length,2);for(const f of defs)assert.match(f.body,/nombre_referencia_pedido_b2b\(pr.id,pr.nombre\)/);
  assert.match(JSON.stringify(defs.find(f=>f.proname==='kora_claim_b2b_pedido_mail').proacl),/service_role/);
  assert.doesNotMatch(JSON.stringify(defs.find(f=>f.proname==='kora_claim_b2b_pedido_mail').proacl),/authenticated/);
  await as(3);
  const catalogue=await q('select * from catalogo_pedidos_b2b()');
  assert.equal(catalogue.length,3,'Colour alternatives merge; ceramic and standard remain distinct');
  const product=catalogue.find(p=>p.id===canonical);
  assert.equal(product.nombre,'Redmi Buds 8 Lite');assert.equal(Number(product.precio_guia),91000);
  assert.deepEqual(Object.keys(product).sort(),['id','codigo','nombre','categoria','foto_url','precio_guia','version_precio'].sort());
  assert.equal((await q('select * from b2b_ofertas')).length,0);
  assert.equal((await q('select * from b2b_mejor_oferta')).length,0);
  assert.equal((await q('select * from b2b_referencias_catalogo')).length,56);
  await assert.rejects(()=>q("update b2b_referencias_catalogo set nombre_pedido='x'"),/permission denied/);
  await assert.rejects(()=>q('select crear_pedido_catalogo_b2b($1::jsonb,null,$2)',[JSON.stringify([{producto_id:blue,cantidad:1,version_precio:product.version_precio,precio_catalogo:91000}]),uid(955)]),/no publicada/);
  await order(product);
  await as(1);
  const chosen=(await q('select f.*,i.producto_id referencia from b2b_pedido_fuente s join b2b_ofertas f on f.id=s.oferta_id join pedido_b2b_items i on i.id=s.pedido_item_id where i.producto_id=$1',[canonical]))[0];
  assert.equal(chosen.producto_id,canonical);assert.equal(Number(chosen.costo),71000);
  // With the generic supplier gone, the lowest coloured source wins, canonical id stable.
  await publish([offer(white,20,85000),offer(blue,20,80000)],'b');
  const winner=(await q('select * from b2b_mejor_oferta'))[0];
  assert.equal(winner.producto_id,canonical);assert.equal(Number(winner.costo),80000);
  assert.equal((await q('select producto_id from b2b_ofertas where id=$1',[winner.id]))[0].producto_id,blue);
  assert.equal((await q('select costo from b2b_ofertas where id=$1',[chosen.id]))[0].costo,'71000.00','historical price is not recalculated');
  await db.exec('reset role');await q("update b2b_ofertas set motivo='[BAJO PEDIDO] Pedido al proveedor' where id=$1",[winner.id]);
  await as(3);
  const refreshed=(await q('select * from catalogo_pedidos_b2b()'))[0];
  assert.equal(refreshed.nombre,'Redmi Buds 8 Lite · Bajo pedido');
  const made=(await order(refreshed,uid(999)))[0].r;
  await as(1);
  const fromColour=(await q('select i.producto_id referencia,f.producto_id origen,f.id oferta from pedido_b2b_items i join b2b_pedido_fuente s on s.pedido_item_id=i.id join b2b_ofertas f on f.id=s.oferta_id where i.pedido_id=$1',[made.pedido_id]))[0];
  assert.deepEqual(fromColour,{referencia:canonical,origen:blue,oferta:winner.id});
  await as(5);assert.equal((await q('select * from b2b_referencias_catalogo')).length,0);
  await assert.rejects(()=>q('select * from catalogo_pedidos_b2b()'),/autorizado/);
  await db.exec('reset role;set role anon');await assert.rejects(()=>q('select * from b2b_referencias_catalogo'),/permission denied/);
  await db.exec('reset role');
  await assert.rejects(()=>q('update b2b_referencias_catalogo set referencia_id=$1 where producto_id=$2',[white,canonical]),/sin cadenas ni ciclos/);
 }finally{await db.close();}
});
