import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { after, before, beforeEach, test } from 'node:test';
import { PGlite } from '@electric-sql/pglite';

const migrations = new URL('../../supabase/migrations/', import.meta.url);
const original = readFileSync(new URL('20260918183628_fusionar_inventario_covenas_en_tolu.sql', migrations), 'utf8');
const correction = readFileSync(new URL('20260919212718_corregir_costos_fusion_covenas_tolu.sql', migrations), 'utf8');
const payload = original.match(/\n\s*'(\[\{"producto_codigo"[\s\S]*?\])'::jsonb/);
assert.ok(payload, 'La prueba usa las filas de la carga original, no importes recreados');
const rows = JSON.parse(payload[1].replaceAll("''", "'"));
const reference = 'ce0db76e-437c-482c-bc82-e7ce61141dc3';
const batch = 'fusion-covenas-tolu-ebf0cb38d37759a1';
const action = 'costos_fusion_covenas_tolu_corregidos';
const firstProduct = '10000000-0000-0000-0000-000000000001';
const firstUnitProduct = '10000000-0000-0000-0000-000000000105';
const firstUnit = '20000000-0000-0000-0000-000000000105';
const otherProduct = '90000000-0000-0000-0000-000000000001';
let db;

async function snapshot() {
  return (await db.query(`select jsonb_build_object(
    'productos',(select jsonb_agg(to_jsonb(p) order by id) from productos p),
    'stock',(select jsonb_agg(to_jsonb(s) order by tienda_codigo,producto_id) from stock_cantidad s),
    'unidades',(select jsonb_agg(to_jsonb(u) order by id) from unidades u),
    'movimientos',(select jsonb_agg(to_jsonb(m) order by id) from movimientos m),
    'ventas',(select jsonb_agg(to_jsonb(v) order by id) from ventas v),
    'venta_items',(select jsonb_agg(to_jsonb(v) order by id) from venta_items v),
    'cortes',(select jsonb_agg(to_jsonb(c) order by id) from inventario_control.cortes c),
    'lineas',(select jsonb_agg(to_jsonb(l) order by id) from inventario_control.lineas l),
    'audit',(select jsonb_agg(to_jsonb(a) order by id) from audit_log a),
    'respaldo',(select jsonb_agg(to_jsonb(r) order by registro_id) from kora_private.respaldo_costos_fusion_tolu_20260919 r)
  ) as data`)).rows[0].data;
}

before(async () => {
  db = await PGlite.create();
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create schema kora_private;
    create schema inventario_control;
    create table kora_private.respaldo_costos_fusion_tolu_20260919(
      registro_id text primary key,detalle jsonb not null,created_at timestamptz not null default now()
    );
    create table public.audit_log(
      id bigint generated by default as identity primary key,usuario text,accion text,tabla text,
      registro_id text,detalle jsonb,created_at timestamptz default now()
    );
    create table public.productos(
      id uuid primary key,codigo text unique,nombre text,categoria text,tipo text,precio_guia numeric,
      activo boolean,created_at timestamptz,foto_url text
    );
    create table public.stock_cantidad(
      producto_id uuid,tienda_codigo text,cantidad integer,costo_promedio numeric,precio_tienda numeric,
      updated_at timestamptz,factura_proveedor_id uuid,primary key(producto_id,tienda_codigo)
    );
    create table public.unidades(
      id uuid primary key,producto_id uuid,imei text unique,estado text,tienda_actual text,
      costo_remision numeric,precio_tienda numeric,created_at timestamptz,
      factura_proveedor_id uuid,remision_item_id uuid
    );
    create table public.movimientos(
      id bigint primary key,tipo text,tienda_codigo text,producto_id uuid,unidad_id uuid,
      cantidad integer,costo numeric,precio numeric,costo_tienda numeric,
      referencia_tipo text,referencia_id text,reverso_de bigint,usuario uuid,nota text,created_at timestamptz
    );
    create table public.ventas(id integer primary key,tienda_codigo text,fecha date);
    create table public.venta_items(
      id integer primary key,venta_id integer,producto_id uuid,unidad_id uuid,
      cantidad integer,precio_venta numeric,costo_tienda_congelado numeric
    );
    create table inventario_control.cortes(id integer primary key,tienda_codigo text);
    create table inventario_control.lineas(id integer primary key,corte_id integer,producto_id uuid);
    create table fixture_filas(n integer primary key,fila jsonb,producto_id uuid,unidad_id uuid);
  `);
  await db.query(`insert into fixture_filas
    select n::integer,fila,('10000000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid,
      case when fila->>'tipo'='serializado' then ('20000000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid end
    from jsonb_array_elements($1::jsonb) with ordinality as f(fila,n)`, [JSON.stringify(rows)]);
});

beforeEach(async () => {
  await db.exec(`
    truncate audit_log,productos,stock_cantidad,unidades,movimientos,ventas,venta_items,
      inventario_control.cortes,inventario_control.lineas,
      kora_private.respaldo_costos_fusion_tolu_20260919 restart identity;
    insert into productos
    select producto_id,fila->>'producto_codigo',fila->>'producto_nombre',fila->>'categoria',
      fila->>'tipo',(fila->>'precio')::numeric,true,'2026-09-18 18:43:05+00',null from fixture_filas;
    insert into stock_cantidad(producto_id,tienda_codigo,cantidad,costo_promedio,precio_tienda,updated_at)
    select producto_id,'CK-01',(fila->>'cantidad')::integer,(fila->>'costo')::numeric,
      (fila->>'precio')::numeric,'2026-09-18 18:43:05+00' from fixture_filas where unidad_id is null;
    insert into unidades(id,producto_id,imei,estado,tienda_actual,costo_remision,precio_tienda,created_at)
    select unidad_id,producto_id,fila->>'imei','disponible','CK-01',(fila->>'costo')::numeric,
      (fila->>'precio')::numeric,'2026-09-18 18:43:05+00' from fixture_filas where unidad_id is not null;
    insert into movimientos(id,tipo,tienda_codigo,producto_id,unidad_id,cantidad,costo,precio,
      costo_tienda,referencia_tipo,referencia_id,nota,created_at)
    select n+6220,'carga_inicial','CK-01',producto_id,unidad_id,(fila->>'cantidad')::integer,
      (fila->>'costo')::numeric,(fila->>'precio')::numeric,(fila->>'costo')::numeric,
      'importacion_excel','${reference}',fila->>'observacion','2026-09-18 18:43:05+00' from fixture_filas;
    insert into audit_log(usuario,accion,tabla,registro_id,detalle)
    values('actor_original','inventario_covenas_fusionado_tolu','inventario','${batch}',
      jsonb_build_object('source_sha256','ebf0cb38d37759a111accd0df180e54a3438f1c4a36aeeec87628c6958542cb1',
        'target_store','CK-01','source_store','CK-11','import_result',jsonb_build_object('referencia_id','${reference}')));

    -- Same product in another shop, unrelated products in Tolú and unrelated dependent records
    -- must neither be modified nor incorrectly block this exact-batch repair.
    insert into productos values('${otherProduct}','AJENO','Otro producto','ACC','cantidad',250,true,'2026-09-01',null);
    insert into stock_cantidad(producto_id,tienda_codigo,cantidad,costo_promedio,precio_tienda,updated_at)
      values('${firstProduct}','CK-02',7,500,600,'2026-09-01'),('${otherProduct}','CK-01',8,150,200,'2026-09-01');
    insert into unidades(id,producto_id,imei,estado,tienda_actual,costo_remision,precio_tienda,created_at)
      values('90000000-0000-0000-0000-000000000002','${firstUnitProduct}','000000000000001',
        'disponible','CK-02',100,150,'2026-09-01');
    insert into movimientos(id,tipo,tienda_codigo,producto_id,cantidad,costo,precio,created_at)
      values(9000,'remision_entrada','CK-02','${firstProduct}',7,500,600,'2026-09-19');
    insert into ventas values(9000,'CK-02','2026-09-19');
    insert into venta_items values(9000,9000,'${firstProduct}',null,1,600,500);
    insert into inventario_control.cortes values(1,'CK-02'),(2,'CK-01');
    insert into inventario_control.lineas values(1,1,'${firstProduct}'),(2,2,'${otherProduct}');
  `);
});

after(async () => db?.close());

test('corrige exactamente los 104 saldos y 10 IMEI de la carga original, con respaldo completo antes/después', async () => {
  assert.equal(rows.length, 114);
  const beforeState = await snapshot();
  await db.exec(correction);
  const afterState = await snapshot();
  const expected = structuredClone(beforeState);
  const costByProduct = new Map(beforeState.movimientos
    .filter(m => m.referencia_id === reference).map(m => [m.producto_id, m.costo]));
  for (const item of expected.stock) {
    if (item.tienda_codigo === 'CK-01' && costByProduct.has(item.producto_id)) item.precio_tienda = costByProduct.get(item.producto_id);
  }
  for (const item of expected.unidades) {
    if (item.tienda_actual === 'CK-01' && costByProduct.has(item.producto_id)) item.precio_tienda = costByProduct.get(item.producto_id);
  }
  const correctedAudit = afterState.audit.filter(a => a.accion === action);
  assert.equal(correctedAudit.length, 1);
  assert.deepEqual({ ...afterState, audit: afterState.audit.filter(a => a.accion !== action), respaldo: null }, expected);

  const detail = correctedAudit[0].detalle;
  assert.equal(detail.stock_corregidos, 104);
  assert.equal(detail.serializados_corregidos, 10);
  assert.equal(detail.referencias, 114);
  assert.equal(detail.unidades, 1372);
  assert.equal(detail.valoracion_erronea, 28934000);
  assert.equal(detail.costo_original_corregido, 13107200);
  assert.equal(detail.import_reference, reference);
  assert.equal(detail.source_audit_id, beforeState.audit[0].id);
  assert.equal(detail.respaldo_registro_id, batch);
  assert.equal(detail.antes, undefined, 'Los costos e IMEI completos no se publican en audit_log');
  assert.equal(detail.despues, undefined);
  assert.equal(afterState.respaldo.length, 1);
  const backup = afterState.respaldo[0];
  assert.equal(backup.registro_id, batch);
  assert.equal(backup.detalle.source_audit_id, beforeState.audit[0].id);
  assert.equal(backup.detalle.import_reference, reference);
  assert.equal(backup.detalle.antes.length, 114);
  assert.equal(backup.detalle.despues.length, 114);
  for (let i = 0; i < backup.detalle.antes.length; i++) {
    const previous = backup.detalle.antes[i];
    const current = backup.detalle.despues[i];
    assert.equal(current.producto_id, previous.producto_id);
    assert.equal(current.unidad_id, previous.unidad_id);
    assert.equal(previous.inventario_antes.precio_tienda, previous.precio);
    assert.deepEqual(current.inventario, { ...previous.inventario_antes, precio_tienda: previous.costo });
    assert.deepEqual(previous.movimiento_antes, beforeState.movimientos.find(m => m.id === previous.id));
    assert.deepEqual(previous.producto_antes, beforeState.productos.find(p => p.id === previous.producto_id));
  }
  const affectedStock = afterState.stock.filter(s => s.tienda_codigo === 'CK-01' && costByProduct.has(s.producto_id));
  const affectedUnits = afterState.unidades.filter(u => u.tienda_actual === 'CK-01' && costByProduct.has(u.producto_id));
  assert.equal(affectedStock.reduce((sum, s) => sum + s.cantidad, 0) + affectedUnits.length, 1372);
  assert.equal(affectedStock.reduce((sum, s) => sum + s.cantidad * s.precio_tienda, 0)
    + affectedUnits.reduce((sum, u) => sum + u.precio_tienda, 0), 13107200);
  assert.equal((await db.query("select relrowsecurity from pg_class where oid='kora_private.respaldo_costos_fusion_tolu_20260919'::regclass")).rows[0].relrowsecurity, true);
  for (const role of ['anon', 'authenticated', 'service_role']) {
    assert.equal((await db.query("select has_table_privilege($1,'kora_private.respaldo_costos_fusion_tolu_20260919','SELECT') as allowed", [role])).rows[0].allowed, false);
  }
});

test('repetir la migración es idempotente y no duplica la auditoría', async () => {
  await db.exec(correction);
  const once = await snapshot();
  await db.exec(correction);
  assert.deepEqual(await snapshot(), once);
});

const guardCases = [
  ['movimiento posterior de accesorio en Tolú', `insert into movimientos(id,tipo,tienda_codigo,producto_id,cantidad) values(9001,'venta','CK-01','${firstProduct}',1)`, /movimientos, ventas o cortes dependientes/],
  ['movimiento del mismo IMEI en otra tienda', `insert into movimientos(id,tipo,tienda_codigo,producto_id,unidad_id,cantidad) values(9001,'traslado','CK-02','${firstUnitProduct}','${firstUnit}',1)`, /movimientos, ventas o cortes dependientes/],
  ['venta de accesorio en Tolú', `insert into ventas values(9001,'CK-01','2026-09-19'); insert into venta_items values(9001,9001,'${firstProduct}',null,1,25000,25000)`, /movimientos, ventas o cortes dependientes/],
  ['venta del mismo IMEI en otra tienda', `insert into venta_items values(9001,9000,'${firstUnitProduct}','${firstUnit}',1,860000,860000)`, /movimientos, ventas o cortes dependientes/],
  ['corte dependiente en Tolú', `insert into inventario_control.lineas values(3,2,'${firstProduct}')`, /movimientos, ventas o cortes dependientes/],
  ['saldo de inventario faltante', `delete from stock_cantidad where tienda_codigo='CK-01' and producto_id='${firstProduct}'`, /114 referencias\/costos verificados/],
  ['costo promedio modificado', `update stock_cantidad set costo_promedio=1 where tienda_codigo='CK-01' and producto_id='${firstProduct}'`, /inventario cambió/],
  ['costo de IMEI modificado', `update unidades set costo_remision=1 where id='${firstUnit}'`, /inventario cambió/],
  ['IMEI reasignado a otro producto', `update unidades set producto_id='${otherProduct}' where id='${firstUnit}'`, /inventario cambió/],
  ['cantidad modificada', `update stock_cantidad set cantidad=cantidad+1 where tienda_codigo='CK-01' and producto_id='${firstProduct}'`, /inventario cambió/],
  ['precio Retail modificado', `update stock_cantidad set precio_tienda=1 where tienda_codigo='CK-01' and producto_id='${firstProduct}'`, /inventario cambió/],
  ['precio comercial modificado', `update productos set precio_guia=1 where id='${firstProduct}'`, /114 referencias\/costos verificados/],
  ['costo del movimiento modificado', `update movimientos set costo_tienda=1 where id=6221`, /114 referencias\/costos verificados/],
];

for (const [description, mutation, error] of guardCases) {
  test(`se detiene sin escrituras parciales: ${description}`, async () => {
    await db.exec(mutation);
    const state = await snapshot();
    await assert.rejects(db.exec(correction), error);
    await db.exec('rollback');
    assert.deepEqual(await snapshot(), state);
  });
}

test('una modificación inesperada de un trigger revierte también los 104 costos ya actualizados', async () => {
  await db.exec(`create function prueba_mutacion_no_permitida() returns trigger language plpgsql as $$
    begin new.imei := 'alterado-' || new.imei; return new; end $$;
    create trigger prueba_mutacion_no_permitida before update on unidades
      for each row execute function prueba_mutacion_no_permitida();`);
  try {
    const state = await snapshot();
    await assert.rejects(db.exec(correction), /dato fuera del costo Retail/);
    await db.exec('rollback');
    assert.deepEqual(await snapshot(), state);
  } finally {
    await db.exec('drop trigger prueba_mutacion_no_permitida on unidades; drop function prueba_mutacion_no_permitida()');
  }
});
