import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';

const migration='supabase/migrations/20260921213525_editar_cuenta_destino_gerencia.sql';
const oscar='6de0ad26-64af-4966-8cd9-d468880af627';
const maite='d1782db6-bacc-4caf-af6f-ce1b8d1c0391';
const andrea='11111111-1111-4111-8111-111111111111';
const beneficiary='22222222-2222-4222-8222-222222222222';
const oldAccount='33333333-3333-4333-8333-333333333333';
const pendingOrder='44444444-4444-4444-8444-444444444444';
const authorizedOrder='55555555-5555-4555-8555-555555555555';

async function database(){
  const db=new PGlite();
  await db.exec(`
    create role anon; create role authenticated;
    create schema auth;
    create function auth.uid() returns uuid language sql as $$
      select nullif(current_setting('test.uid',true),'')::uuid
    $$;
    create table public.perfiles(id uuid primary key,rol text not null,activo boolean not null);
    create table public.liquidation_beneficiaries(id uuid primary key,nombre text,identificacion text,activo boolean not null);
    create table public.beneficiary_bank_accounts(
      id uuid primary key default gen_random_uuid(),beneficiary_id uuid not null,banco text not null,
      tipo_cuenta text not null,numero_cuenta text not null,validada boolean not null default false,
      validada_por uuid,validada_at timestamptz,activo boolean not null default true,created_at timestamptz default now(),
      unique(beneficiary_id,numero_cuenta)
    );
    create table public.payment_orders(
      id uuid primary key,beneficiary_id uuid not null,bank_account_id uuid,bank_snapshot jsonb,
      estado text not null,authorized_by uuid,authorized_at timestamptz,paid_by uuid,fecha_pagada timestamptz,
      soporte_path text,updated_at timestamptz default now()
    );
    create table public.audit_log(
      id bigint generated by default as identity primary key,usuario uuid,accion text,tabla text,
      registro_id uuid,detalle jsonb not null default '{}'::jsonb,created_at timestamptz default now()
    );
    create function public.proteger_destino_pago() returns trigger language plpgsql as $$begin return new;end$$;
    create trigger zzzz_proteger_destino_pago before update on public.payment_orders
      for each row execute function public.proteger_destino_pago();
    insert into perfiles values
      ('${oscar}','gerencia',true),('${maite}','auditoria',true),('${andrea}','admin_tienda',true);
    insert into liquidation_beneficiaries values('${beneficiary}','Titular prueba','123456789',true);
    insert into beneficiary_bank_accounts(id,beneficiary_id,banco,tipo_cuenta,numero_cuenta,validada,activo)
      values('${oldAccount}','${beneficiary}','BANCO PRUEBA','ahorros','001234567',true,true);
    insert into payment_orders values
      ('${pendingOrder}','${beneficiary}','${oldAccount}',jsonb_build_object('account_number','001234567'),'pendiente',null,null,null,null,null,now()),
      ('${authorizedOrder}','${beneficiary}','${oldAccount}',jsonb_build_object('account_number','001234567'),'programado','${oscar}',now(),null,null,null,now());
  `);
  await db.exec(readFileSync(migration,'utf8'));
  return db;
}

test('la base restringe la edición y conserva pagos autorizados',async()=>{
  const db=await database();
  try{
    await db.exec(`select set_config('test.uid','${andrea}',false)`);
    await assert.rejects(
      db.query(`select public.tesoreria_editar_cuenta_destino('${oldAccount}','009876543','Corrección confirmada')`),
      /Solo Mayte y Oscar/
    );

    await db.exec(`select set_config('test.uid','${maite}',false)`);
    const result=(await db.query(`select public.tesoreria_editar_cuenta_destino('${oldAccount}','009876543','Titular confirmó cuenta nueva') result`)).rows[0].result;
    assert.equal(result.ok,true);
    assert.equal(result.ordenes_pendientes_actualizadas,1);

    const accounts=(await db.query(`select id,numero_cuenta,activo from beneficiary_bank_accounts order by numero_cuenta`)).rows;
    assert.equal(accounts.find(row=>row.id===oldAccount).activo,false);
    const newAccount=accounts.find(row=>row.numero_cuenta==='009876543');
    assert.equal(newAccount.activo,true);

    const orders=(await db.query(`select id,bank_account_id,bank_snapshot from payment_orders order by id`)).rows;
    assert.equal(orders.find(row=>row.id===pendingOrder).bank_account_id,newAccount.id);
    assert.equal(orders.find(row=>row.id===pendingOrder).bank_snapshot.account_number,'009876543');
    assert.equal(orders.find(row=>row.id===authorizedOrder).bank_account_id,oldAccount);
    assert.equal(orders.find(row=>row.id===authorizedOrder).bank_snapshot.account_number,'001234567');

    const audit=(await db.query(`select accion,detalle from audit_log`)).rows[0];
    assert.equal(audit.accion,'cuenta_destino_editada');
    assert.equal(audit.detalle.ordenes_pendientes_actualizadas,1);
    assert.equal(audit.detalle.ordenes_autorizadas_o_pagadas_modificadas,0);

    await db.exec(`select set_config('test.uid','${andrea}',false)`);
    await assert.rejects(
      db.query(`insert into beneficiary_bank_accounts(beneficiary_id,banco,tipo_cuenta,numero_cuenta,validada,activo) values('${beneficiary}','BANCO PRUEBA','ahorros','007777777',true,true)`),
      /Solo Mayte y Oscar pueden reemplazar/
    );
  }finally{await db.close();}
});

test('la protección histórica rechaza reemplazar la cuenta de una orden autorizada',async()=>{
  const db=await database();
  try{
    await db.exec(`select set_config('test.uid','${oscar}',false)`);
    await db.query(`select public.tesoreria_editar_cuenta_destino('${oldAccount}','008888888','Cambio de cuenta confirmado')`);
    const newId=(await db.query(`select id from beneficiary_bank_accounts where numero_cuenta='008888888'`)).rows[0].id;
    await assert.rejects(
      db.query(`update payment_orders set bank_account_id=$1,bank_snapshot=jsonb_build_object('account_number','008888888') where id='${authorizedOrder}'`,[newId]),
      /cuenta histórica no se puede reemplazar/
    );
  }finally{await db.close();}
});
