-- Dependencias mínimas para validar Creditek Aliados en Supabase local.
-- No contiene usuarios, contraseñas ni datos productivos.
begin;

create table if not exists public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  rol text not null check (rol in ('gerencia','auditoria','admin_tienda','asesor')),
  activo boolean not null default true,
  tienda_codigo text,
  created_at timestamptz not null default now()
);

create table if not exists public.ejecutivos (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.origenes (
  codigo text primary key,
  nombre text not null,
  tipo text not null check (tipo in ('propia','aliado')),
  ejecutivo_id uuid references public.ejecutivos(id),
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  usuario uuid references public.perfiles(id),
  accion text not null,
  tabla text not null,
  registro_id uuid,
  detalle jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public, file_size_limit)
values ('soportes', 'soportes', false, 10485760)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit;

alter table public.perfiles enable row level security;
alter table public.ejecutivos enable row level security;
alter table public.origenes enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists perfiles_propio on public.perfiles;
create policy perfiles_propio on public.perfiles
for select to authenticated using (id = auth.uid());

drop policy if exists ejecutivos_autenticados on public.ejecutivos;
create policy ejecutivos_autenticados on public.ejecutivos
for select to authenticated using (true);

drop policy if exists origenes_autenticados on public.origenes;
create policy origenes_autenticados on public.origenes
for select to authenticated using (true);

grant select on public.perfiles, public.ejecutivos, public.origenes to authenticated;
grant all on public.perfiles, public.ejecutivos, public.origenes, public.audit_log to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;
